### ISSUE TITLE
c++ 11 version

### ISSUE THREAD

**Issue by rjjrbatarao** [HaniAmmar/Qentem-Engine#2]
maybe theres a c++ 11 version of this so we can use this on arduino or espidf environment

**Comment by HaniAmmar** [comment]
May I ask how are you using this for Arduino?

Because I used c++17 for inline static in tests, the rest is just namespace rewrite and 'if constexpr'

**Comment by HaniAmmar** [comment]
I have checked ESP-IDF, and I don't see any reason preventing it from working. As for c++11, I did some changes that will make it much easier to be ported it back to  c++11, you just need to find all 'if constexpr' and replace them with 'if'. However, I don't think it will work with Arduino, because FindFirstBit() and FindLastBit() need to be implemented by code. it's doable, but I do not see a reason to do it. If you need to, you can use this code:

https://github.com/HaniAmmar/Qentem-Engine/commit/d89b45efcd43a4b56812187a66de3d952c86c58a

**Comment by rjjrbatarao** [comment]
this is just awesome !! thank you for the latest update compiles fine now on esp32 arduino ide :)

**Comment by HaniAmmar** [comment]
You are welcome!

I just add a change that may have a great impact on memory usage by reducing it to 2/3, which will improve the performance when compiled out off the box on 32-bit CPU, the change should set SizeT to SizeT16 (unsigned short) since it's SizeT32 on 64-bit. Try it and let me know. Also check Common.hpp for preprocessor directive that you may find useful.

Q: Did you implement FindFirstBit() and FindLastBit()? I'm asking because I never tried Arduino, and never even thought this code might work in environments like those. Maybe because I implemented everything I needed, and I did that because I do not want to go back and change something because It got changed in the STL. I had that problem with other frameworks before.

Let me know if you did, I might try to add a workaround so you don't have to rebase the code every time I change something.
