### ISSUE TITLE
Passing data from a template to a Callback function feature

### ISSUE THREAD

**Issue by rjjrbatarao** [HaniAmmar/Qentem-Engine#6]
I was thinking of a way to pass data from the template to a native function to process it with any scripting engine. This is not what template engine is for. maybe it will be helpful to some in the future.
What does the feature solves? 
* prevent recompiling 
* update and add any functionality to code just by editing the template
* sky is the limit since it does not choose which scripting engine you can use to process the data, you can even use c++ to process the data
The following is what i want to achieve ie. the ```<exec></exec>``` element which calls a native callback_function

```c++
#include "JSON.hpp"
#include "Template.hpp"

#include <iostream>

using Qentem::StringStream;
using Qentem::Template;
using Qentem::Value;
using Qentem::JSON;


void callback_function(char* data){
  // process data here 
  // something to execute the data here like micropython scripting or embedded javascript etc
  return "this content will be displayed inside exec or just return empty"
}

int main() {


    Value<char> value = JSON::Parse(R"(
[
    {
        "major": "Computer Science",
        "students": [
            { "Name": "Student1", "GPA": 3.2 },
            { "Name": "Student2", "GPA": 3.8 },
            { "Name": "Student3", "GPA": 2.8 }
        ]
    },
    {
        "major": "Math",
        "students": [
            { "Name": "Student4", "GPA": 3.0 },
            { "Name": "Student5", "GPA": 2.5 },
            { "Name": "Student6", "GPA": 2.4 }
        ]
    }
]
    )");

    const char *content = R"(
<html>
<body>
    <div>
        <h2>Students' list:</h2>
        <exec name="cb1" data=" 
               from sys import argv
               f = open('example.txt', 'r')
               file_contents = f.read()
               print (file)">
       </exec>
        <loop value="department_val">
            <h3>Major: {var:department_val[major]}</h3>
            <ul>
            <loop set="department_val[students]" value="student_val">
                <li>
                    <span>Name: {var:student_val[Name]}</span>
                    <span>
                        GPA: {var:student_val[GPA]}
                        <if case="{var:student_val[GPA]} < 2.5"> (Inform adviser!)
                        <elseif case="{var:student_val[GPA]} >= 3.5" /> (President's List!)
                        <elseif case="{var:student_val[GPA]} >= 3.0" /> (Dean's List!)
                        </if>
                    </span>
                </li>
            </loop>
            </ul>
        </loop>
    </div>
</body>

</html>
)";

    StringStream<char> stream;

    Template::Render(content, value, stream);
    Template::AddCallback(callback_function, "cb1" ,stream);
    std::cout << stream << '\n';
}
```

**Comment by HaniAmmar** [comment]
Helo,

My understanding of what you're asking is to make Template::Render plugable. However, Template::Render is the most important function in the entire project; everything else is built to support it. This was the first function I wrote, and then I added the rest to improve and extend its functionality.

What I'm trying to say is that Template::Render() is at the top of every function, so it's easy to export it as a C function. Don't get me wrong, I have used callbacks, and I'm using them now with Value.hpp::CopyValueTo() because it's very convenient to have it. but I don't think it is in this case.

The difference between Render() and CopyValueTo() is that the latter needs Init(); Render() does not; it needs the template (char *) and some type of value holder, and it does not have to be Qentem::Value.

I'm all for what makes Qentem better and easier to use, but before I add a plugable Render(), I would like you to check these out:

https://github.com/HaniAmmar/JQen/blob/main/Source/QLib.cpp#L9
https://github.com/HaniAmmar/PiQen/blob/main/piqen.cpp#L18
https://github.com/HaniAmmar/BQen/blob/main/bqen.cpp#L13

in PHP, I do not use Qentem::Value:
https://github.com/HaniAmmar/BQen/blob/main/bqen.hpp#L18

I want to touch on usability in general. The content of templates should be stored in files (*.html) or in a database. The idea of value is meant to be generated from anything, but SQL would be a great option. JSON was added to be used as a medium, which enabled me to use Qentem in the browser. I could dig deeper into the API and read the values with no need to export them to JSON, but personally, it will take too much time, and it's not needed because by the time the data reaches the browser, it would have to be in JSON format anyway, and Qentem can do anything in the browser, like it does in C++.

But let's say I understood you wrong, and all you want is a function to be called just before Qentem::Render() reads the content, like a hook, to change something in the content based on some algorithm; you can do that with just a wrapper around Qentem::Render(), I will help you code it if you like.

I'm not against adding a callback feature, but I think this one can be implemented much better in the library that calls it, unless I missed something. Because once I implement it in a function, you will be limited to that function only, and then your entire code will be limited.

**Comment by HaniAmmar** [comment]
I recently added this:
https://github.com/HaniAmmar/Qentem-Engine/blob/main/Examples/Template/Template17.cpp

CachedRender() is just a wrapper with a hash-table.

**Comment by rjjrbatarao** [comment]
i thought of something can be exposed from the library but this example would suffice
